/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.PedidoDespacho;
import Models.PedidoFinal;
import java.awt.Container;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EnzoV
 */
public class InformeDespacho extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleDespacho
     */
    DefaultTableModel model = new DefaultTableModel();
    String[] datos = new String[4]; // Tres columnas: Boleta, Monto, Medio
    Container p_padre = null;

    public InformeDespacho(Container padre) {
        initComponents();
        p_padre = padre;
        this.setLocation(110, 10);
        model.addColumn("Fecha");
        model.addColumn("Boleta");
        model.addColumn("Tiempo");
        model.addColumn("Estado");
        tablepedido.setModel(model);
        Listar("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepedido = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblatiempo = new javax.swing.JLabel();
        lbltarde = new javax.swing.JLabel();
        fechafiltrar = new com.toedter.calendar.JDateChooser();
        btnfiltrar = new javax.swing.JButton();
        lbltotal = new javax.swing.JLabel();
        btndetalle = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INFORME DE DESPACHO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Pedidos Despachados");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Pedidos A Tiempo");

        tablepedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Boleta", "Tiempo", "Estado"
            }
        ));
        tablepedido.setToolTipText("");
        jScrollPane1.setViewportView(tablepedido);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Pedidos Tardios");

        lblatiempo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblatiempo.setText("0");

        lbltarde.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbltarde.setText("0");

        btnfiltrar.setText("Filtrar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        lbltotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbltotal.setText("0");

        btndetalle.setText("Ver Detalle");
        btndetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblatiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbltarde)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btndetalle))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbltotal)
                                .addGap(40, 40, 40)
                                .addComponent(fechafiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnfiltrar)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbltotal))
                    .addComponent(btnfiltrar)
                    .addComponent(fechafiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblatiempo)
                    .addComponent(lbltarde))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndetalle)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Listar(String fecha) {
        int total = 0;
        int total_esperado = 0;
        int total_tardio = 0;
        CAdmin admin = new CAdmin();
        List<PedidoDespacho> pedidos = admin.ListarPedidosDespacho(fecha);

        for (PedidoDespacho pedido : pedidos) {
            String estado = pedido.getEstado();
            String texto_tiempo = "";
            int tiempo_segundos = pedido.getTiempo();
            int tiempo_minutos = 0;
            int restante_minutos = 0;
            int tiempo_horas = 0;
            int restante_horas = 0;

            if (tiempo_segundos >= 3600) {
                tiempo_horas = tiempo_segundos / 3600;
                restante_horas = tiempo_segundos % 3600;
                tiempo_minutos = restante_horas / 60;
                restante_minutos = restante_horas % 60;
                texto_tiempo = tiempo_horas + ":" + tiempo_minutos + ":" + restante_minutos;
            } else if (tiempo_segundos >= 60 && tiempo_segundos < 3600) {
                tiempo_minutos = tiempo_segundos / 60;
                restante_minutos = tiempo_segundos % 60;
                texto_tiempo = tiempo_minutos + ":" + restante_minutos;
            } else {
                texto_tiempo = "0:"+ String.valueOf(tiempo_segundos);
            }

            datos[0] = pedido.getFecha();
            datos[1] = pedido.getCod_boleta();
            datos[2] = texto_tiempo;
            datos[3] = estado;
            model.addRow(datos);
            total += 1;
            if (estado.equals("Tardio")) {
                total_tardio += 1;
            } else {
                total_esperado += 1;
            }
        }
        lbltotal.setText(String.valueOf(total));
        lbltarde.setText(String.valueOf(total_tardio));
        lblatiempo.setText(String.valueOf(total_esperado));
    }


    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        Calendar fecha_filtrar = fechafiltrar.getCalendar();
        if (fecha_filtrar != null) {
            model.setRowCount(0);

            SimpleDateFormat fechaFormatter = new SimpleDateFormat("dd-MM-yyyy");
            String fechaFormateada = fechaFormatter.format(fecha_filtrar.getTime());
            Listar(fechaFormateada);
        } else
            JOptionPane.showMessageDialog(null, "Inserta fecha", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btndetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetalleActionPerformed
        int selectedRow = tablepedido.getSelectedRow();
        String boleta = tablepedido.getValueAt(selectedRow, 1).toString();
        String tiempo = tablepedido.getValueAt(selectedRow, 2).toString();
        String estado = tablepedido.getValueAt(selectedRow, 3).toString();

        
        DetalleDespacho despacho = new DetalleDespacho(boleta, tiempo,estado);
        
        p_padre.add(despacho);
        despacho.setVisible(true);
        dispose();
    }//GEN-LAST:event_btndetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndetalle;
    private javax.swing.JButton btnfiltrar;
    private com.toedter.calendar.JDateChooser fechafiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblatiempo;
    private javax.swing.JLabel lbltarde;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tablepedido;
    // End of variables declaration//GEN-END:variables
}
