/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.PedidoProd;
import Models.Producto;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author valen
 */
public class VentanaMesa extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMesa
     */
    private String ruta = "src/JSON/BD.JSON";
    String nombre_mesa;
    String opcion = "agregar";
    String m_pedido = "El menu seleccionado es: \n";
    int id_suc, id_mesa2, id_pedido;
    CAdmin cAdmin = new CAdmin();
    List<Producto> productos = null;
    List<PedidoProd> pedidocompleto = null;
    List<PedidoProd> pedidonuevo = new ArrayList<>();

    public VentanaMesa(String n_mesa, int id_usuario, int id_sucursal, int id_mesa) {
        initComponents();
        lblnombre.setText(n_mesa);
        id_suc = id_sucursal;
        id_mesa2 = id_mesa;
        nombre_mesa = n_mesa;

        DefaultListModel<String> listModel = new DefaultListModel<>();
        DefaultListModel<String> listModel2 = new DefaultListModel<>();
        DefaultListModel<String> listModel3 = new DefaultListModel<>();
        DefaultListModel<String> listModel4 = new DefaultListModel<>();

        jListentradas.setModel(listModel);
        jListplato.setModel(listModel2);
        jlistbebidas.setModel(listModel3);
        jlistpostres.setModel(listModel4);

        productos = cAdmin.ListarProductos(id_sucursal);

        for (Producto producto : productos) {

            if (producto.getId_cat() == 1) {
                listModel.addElement((String) producto.getNom_Producto());
            }
            if (producto.getId_cat() == 2) {
                listModel2.addElement((String) producto.getNom_Producto());
            }
            if (producto.getId_cat() == 3) {
                listModel3.addElement((String) producto.getNom_Producto());
            }
            if (producto.getId_cat() == 4) {
                listModel4.addElement((String) producto.getNom_Producto());
            }

        }

        pedidocompleto = cAdmin.Listarpedidomesa(id_mesa);

        for (PedidoProd pedidoProd : pedidocompleto) {
            m_pedido += pedidoProd.getNom_Prod() + "\n";
            txtPedido.setText(m_pedido);
        }

        if (pedidocompleto.size() > 0) {
            id_pedido = pedidocompleto.get(0).getId_pedido();
        } else {
            id_pedido = cAdmin.UltimoIDPedido(id_mesa) + 1;
        }

        if (txtPedido.getText().length() > 0) {
            opcion = "editar";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistbebidas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListentradas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListplato = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlistpostres = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        BotonAgr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombre.setText("MESA1");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlistbebidas);

        jScrollPane3.setViewportView(jListentradas);

        jScrollPane4.setViewportView(jListplato);

        jScrollPane5.setViewportView(jlistpostres);

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BotonAgr.setText("Agregar");
        BotonAgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgrActionPerformed(evt);
            }
        });

        txtPedido.setColumns(20);
        txtPedido.setRows(5);
        txtPedido.setEnabled(false);
        jScrollPane1.setViewportView(txtPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lblnombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(BotonAgr))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton3)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombre)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonAgr)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String mensaje = "";


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtPedido.getText().getBytes().length > 0) {
            VentanaCobro v2 = new VentanaCobro(nombre_mesa, pedidocompleto);
            v2.setVisible(true);
            dispose();
        } else
            JOptionPane.showMessageDialog(null, "Agrega pedido a mesa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BotonAgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgrActionPerformed

        agregar_producto(jListentradas);
        agregar_producto(jlistbebidas);
        agregar_producto(jListplato);
        agregar_producto(jlistpostres);

        mensaje += m_pedido;
        txtPedido.setText(mensaje);

        cAdmin.AgregarPedido(pedidonuevo, id_mesa2);

    }//GEN-LAST:event_BotonAgrActionPerformed

    private void agregar_producto(JList<String> lista) {
        String select_producto = lista.getSelectedValue();
        if (select_producto != null) {
            String nombre_producto = select_producto;
            m_pedido += nombre_producto + "\n";
            int id_producto = cAdmin.GetIDProducto(nombre_producto, id_suc);
            Optional<Producto> producto  = productos.stream().filter(producto2 -> producto2.getId_Producto() == id_producto).findFirst();
            double precio = producto.get().getPrecio_Producto();
            int tiempo = producto.get().getTime_Producto();
            
            pedidonuevo.add(new PedidoProd(id_pedido, id_producto, nombre_producto,precio, id_mesa2,tiempo));
            pedidocompleto.add(new PedidoProd(id_pedido, id_producto, nombre_producto,precio, id_mesa2,tiempo));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String mesa = "";
                int id_usu = 0, id_suc = 0, id_mesa = 0;
                new VentanaMesa(mesa, id_usu, id_suc, id_mesa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jListentradas;
    private javax.swing.JList<String> jListplato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> jlistbebidas;
    private javax.swing.JList<String> jlistpostres;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables

    Object get(String mesa) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
