/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.Mesa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author EnzoV
 */
public class VistaMesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMesa
     */
    private String ruta = "src/JSON/BD.JSON";
    CAdmin admin = new CAdmin();
    public VistaMesa(int id_usu, int id_suc) {
        initComponents();
        int x = 20;
        int y = 20;
        List<Mesa> mesas = admin.ListarMesa(id_suc);
        for (int i = 0; i < mesas.size(); i++) {
            if (i % 3 == 0 & i > 0) {
                x = 20;
                y += 70;
            }

            Mesa mesa = mesas.get(i);
            String n_mesa = mesa.getNom_mesa();
            String disponibilidad_mesa = mesa.getDisponible();
            int id_mesa = mesa.getId_mesa();
            JButton boton_mesa = new JButton();
            boton_mesa.setBounds(x, y, 110, 50);

            if (disponibilidad_mesa.equals("no")) {
                boton_mesa.setBackground(Color.red);
                boton_mesa.setForeground(Color.white);
            }

            boton_mesa.addActionListener(
                    (ActionEvent e) -> {
                        VentanaMesa vmesa = new VentanaMesa(n_mesa, id_usu,id_suc,id_mesa);
                        vmesa.setVisible(true);
                        dispose();
                    }
            );
            boton_mesa.setText(n_mesa);
            boton_mesa.setVisible(true);
            PanelMesas.add(boton_mesa);
            x += 130;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelMesas = new javax.swing.JPanel();

        setResizable(true);

        jLabel1.setText("LISTADO DE MESAS");

        javax.swing.GroupLayout PanelMesasLayout = new javax.swing.GroupLayout(PanelMesas);
        PanelMesas.setLayout(PanelMesasLayout);
        PanelMesasLayout.setHorizontalGroup(
            PanelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelMesasLayout.setVerticalGroup(
            PanelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMesas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
