/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.PedidoFinal;
import java.awt.Color;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author EnzoV
 */
public class VistaDespacho extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDespacho
     */
    private Timer timer;
    private int realsegundos = 0;
    private JCheckBox[] checkboxes;
    private String ruta = "src/JSON/BD.JSON";

    public VistaDespacho(int id_sucursal) {
        initComponents();
        CAdmin admin = new CAdmin();

        List<PedidoFinal> pedidos = admin.ListarPedidos(id_sucursal);

        List<Integer> ids_pedidos = pedidos.stream().map(PedidoFinal::getID_Ped).distinct().collect(Collectors.toList());

        int xpanel = 20;
        int ypanel = 20;

        for (int id_pedido : ids_pedidos) {

            int contar = 1;
            List<PedidoFinal> pedidoFinals = pedidos.stream().filter(persona -> persona.getID_Ped() == id_pedido).collect(Collectors.toList());
            int sizepanel = CrearPedido(pedidoFinals, xpanel, ypanel);
            xpanel += 320;
            if (contar % 2 == 0 & contar > 0) {
                xpanel = 20;
                ypanel += sizepanel + 50;
            }
            contar++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    CAdmin cDespacho = new CAdmin();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPMain = new javax.swing.JPanel();

        setClosable(true);
        setResizable(true);

        javax.swing.GroupLayout JPMainLayout = new javax.swing.GroupLayout(JPMain);
        JPMain.setLayout(JPMainLayout);
        JPMainLayout.setHorizontalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        JPMainLayout.setVerticalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int CrearPedido(List<PedidoFinal> pedidosProd, int xpanel, int ypanel) {
        int sizepanel = 120 + (pedidosProd.size() * 20);
        int xmargen_izq = 10;
        int ytitleproducto = 28;
        int xtitlecantidad = 150;
        int ytitlecantidad = 28;
        int xboton = 110;

        //  int ynombre= xpanel+30;
        //Panel
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBounds(xpanel, ypanel, 252, sizepanel);
        Border bordepanel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK); // Borde lineal en la parte inferior
        panel.setBorder(bordepanel);
        panel.setVisible(true);

        //Tiempo
        JLabel etiqueta_tiempo = new JLabel();
        etiqueta_tiempo.setBounds(xmargen_izq, 5, 86, 16);
        etiqueta_tiempo.setText("Tiempo");
        etiqueta_tiempo.setVisible(true);

        timer = new Timer(1000, new ActionListener() {
            int horas = 0, minutos = 0, segundos = 0;

            public void actionPerformed(ActionEvent e) {
                realsegundos++;
                segundos++;
                if (segundos > 0 & segundos % 60 == 0) {
                    segundos = 0;
                    minutos++;
                }
                if (minutos > 0 & minutos % 60 == 0) {
                    minutos = 0;
                    horas++;
                }
                // La acción que quieres realizar en cada intervalo
                if (horas > 0) {
                    etiqueta_tiempo.setText("Tiempo: " + horas + ":" + minutos + ":" + segundos);
                } else if (minutos > 0) {
                    etiqueta_tiempo.setText("Tiempo: " + minutos + ":" + segundos);
                } else {
                    etiqueta_tiempo.setText("Tiempo: " + segundos);
                }
            }
        });
        timer.start();

        //Productos
        Label etiqueta_titprod = new Label();
        etiqueta_titprod.setText("Productos");
        etiqueta_titprod.setBounds(xmargen_izq, ytitleproducto, 80, 16);
        etiqueta_titprod.setVisible(true);

        //Cantidad
        JLabel etiqueta_titcant = new JLabel();
        etiqueta_titcant.setBounds(xtitlecantidad, ytitlecantidad, 86, 16);
        etiqueta_titcant.setText("Cantidad");
        etiqueta_titcant.setVisible(true);

        int ypanelcontainer = ypanel + 30;

        for (PedidoFinal pedido : pedidosProd) {

            JPanel panelproducto = new JPanel();
            panelproducto.setLayout(null);
            panelproducto.setBounds(xmargen_izq, ypanelcontainer, 240, 30);

            Label etiqueta_prod = new Label();
            etiqueta_prod.setText((String) pedido.getNom_Prod());
            etiqueta_prod.setBounds(0, 10, 120, 16);
            etiqueta_prod.setVisible(true);

            JLabel etiqueta_cant = new JLabel();
            etiqueta_cant.setText(String.valueOf(1));
            etiqueta_cant.setBounds(170, 10, 20, 16);
            etiqueta_cant.setVisible(true);

            panelproducto.add(etiqueta_cant);
            panelproducto.add(etiqueta_prod);
            panelproducto.setVisible(true);
            panel.add(panelproducto);

            ypanelcontainer += 25;
        }

        JButton boton_despachartodo = new JButton();

        boton_despachartodo.setText("DESPACHAR");
        boton_despachartodo.setBounds(xboton, ypanelcontainer + 10, 130, 30);
        boton_despachartodo.setVisible(true);

        panel.add(etiqueta_titcant);
        panel.add(etiqueta_tiempo);
        panel.add(etiqueta_titprod);
        panel.add(boton_despachartodo);
        JPMain.add(panel);

        boton_despachartodo.addActionListener(
                (ActionEvent e) -> {
                            LocalTime horaActual = LocalTime.now();

                    String respuesta = cDespacho.Despacho(pedidosProd, horaActual,pedidosProd.get(0).getID_Ped());
                    if (respuesta.equals("Se entrego a tiempo")) {
                        JOptionPane.showMessageDialog(null, respuesta, "Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, respuesta, "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    JPMain.remove(panel);
                    JPMain.updateUI();
                }
        );
        return sizepanel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPMain;
    // End of variables declaration//GEN-END:variables
}
