/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.Usuario;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author EnzoV
 */
public class VistaPerfiles extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaPerfiles
     */
    Container p_padre = null;
    private String ruta = "src/JSON/BD.JSON";
    int id_admin = 0;
    String opcion;
    CAdmin admin = new CAdmin();

    public VistaPerfiles(Container padre, int id_usu) throws ParseException {
        initComponents();
        this.setLocation(110, 10);
        id_admin=id_usu;
        p_padre = padre;
        int pos_y = 50;

        int id_res = admin.ObtenerIdRes(id_usu);
        List<Usuario> usuarios = admin.ListarUsuario(id_res);

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario usuario = usuarios.get(i);

            String estado = (String) usuario.getEstado_usuario();
            JPanel panel = new JPanel();
            panel.setLayout(null);
            panel.setBounds(0, pos_y, 350, 41);

            JLabel etiqueta = new JLabel();
            if (estado.equals("Inactivo")) {
                etiqueta.setForeground(Color.GRAY);
            }
            etiqueta.setBounds(10, 15, 150, 30); // Set position and size (x, y, width, height)
            etiqueta.setText(usuario.getNombre_usuario());
            panel.add(etiqueta);
            etiqueta.setVisible(true);

            JLabel etiqueta2 = new JLabel();
            etiqueta2.setBounds(80, 15, 150, 30); // Set position and size (x, y, width, height)
            etiqueta2.setText((String) usuario.getEstado_usuario());
            panel.add(etiqueta2);
            etiqueta2.setVisible(true);

            //Boton Editar
            JButton button = new JButton();
            button.setBackground(Color.yellow);
            button.setText("Editar");
            button.setBounds(150, 15, 80, 30); // Set position and size (x, y, width, height)

            button.addActionListener((ActionEvent e) -> {
                opcion = "editar";
                setVisible(false);

                //abrir form
                EditarPerfil editarPerfil = new EditarPerfil(padre, usuario, opcion,id_admin);
                padre.add(editarPerfil);
                editarPerfil.setVisible(true);
            });
            panel.add(button);           

            Border bordeInferior = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK); // Borde lineal en la parte inferior
            panel.setBorder(bordeInferior);
            panel.setVisible(true);

            JFondo.add(panel);
            pos_y += 40;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFondo = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suma-signo-mas.png"))); // NOI18N
        btnagregar.setText("Nuevo");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JFondoLayout = new javax.swing.GroupLayout(JFondo);
        JFondo.setLayout(JFondoLayout);
        JFondoLayout.setHorizontalGroup(
            JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        JFondoLayout.setVerticalGroup(
            JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        setVisible(false);
        opcion = "agregar";
        Usuario usuario = new Usuario(0, "", "", "",0, "", "");
        EditarPerfil editarPerfil = new EditarPerfil(p_padre, usuario, opcion,id_admin);
        p_padre.add(editarPerfil);
        editarPerfil.setVisible(true);
    }//GEN-LAST:event_btnagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JFondo;
    private javax.swing.JButton btnagregar;
    // End of variables declaration//GEN-END:variables
}
