/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CAdmin;
import Models.Categoria;
import Models.Producto;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author EnzoV
 */
public class VistaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaProductos
     */
    List<Categoria> categorias = new ArrayList<>();
    private String ruta = "src/JSON/BD.JSON";

    Container p_padre = null;
    Boolean p_estado = null;

    int last_iduser = 0;
    String opcion;
    CAdmin admin = new CAdmin();

    public VistaProductos(Container padre, boolean estado, int id_sucursal) {
        initComponents();
        this.setLocation(110, 10);
        int pos_y = 15;
        int pos_y_cat = 15;
        p_padre = padre;
        p_estado = estado;

        categorias = admin.ListarCategorias(id_sucursal);
        List<Producto> productos = admin.ListarProductos(id_sucursal);
        //Categoria
        for (int i = 0; i < categorias.size(); i++) {
            Categoria categoria = categorias.get(i);
            CrearBotonCat((String) categoria.getNom_categoria(), pos_y, categoria.getId_categoria(), productos);
            pos_y += 40;
        }

        //Producto
        for (int i = 0; i < productos.size(); i++) {
            Producto producto = productos.get(i);
            
            int id_producto = producto.getId_Producto();
            String nombre = (String) producto.getNom_Producto();
            int id_categoria = producto.getId_cat();
            CrearElementoProducto(nombre, pos_y_cat, padre, estado, producto, id_categoria, id_producto);
            pos_y_cat += 40;

        }
    }

    private void CrearElementoProducto(String nombre, int pos_y_cat, Container padre, Boolean estado, Producto producto, int id_categoria, int id_producto) {
        JLabel etiqueta = new JLabel(nombre);
        etiqueta.setBounds(0, pos_y_cat, 150, 30); // Set position and size (x, y, width, height)
        PanelProductos.add(etiqueta);
        // Make the frame visible
        PanelProductos.setVisible(true);

        JButton button = new JButton("Editar");
        button.setBounds(150, pos_y_cat, 100, 30); // Set position and size (x, y, width, height)
        PanelProductos.add(button);
        // Make the frame visible
        PanelProductos.setVisible(true);
        button.addActionListener((ActionEvent e) -> {
            opcion = "editar";

            setVisible(estado);
            //abrir form
            EditarProducto editarProducto = new EditarProducto(padre, categorias, producto, id_producto, opcion, id_categoria);
            padre.add(editarProducto);
            editarProducto.setVisible(true);
        });
    }

    private void CrearBotonCat(String nombre, int pos_y, int idcategoria, List<Producto> productos) {

        JButton button = new JButton(nombre);
        button.setBounds(5, pos_y, 100, 30); // Set position and size (x, y, width, height)
        PanelCat.add(button);
        // Make the frame visible
        PanelCat.setVisible(true);
        button.addActionListener((ActionEvent e) -> {
            int pos_prod_y = 15;
            PanelProductos.removeAll();
            for (int i = 0; i < productos.size(); i++) {
                Producto producto = productos.get(i);
                if (producto.getId_cat() == idcategoria) {
                    CrearElementoProducto(producto.getNom_Producto(), pos_prod_y, p_padre, p_estado, producto, idcategoria, producto.getId_Producto());
                    pos_prod_y += 40;
                }
            }
            PanelProductos.updateUI();

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCat = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        PanelProductos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout PanelCatLayout = new javax.swing.GroupLayout(PanelCat);
        PanelCat.setLayout(PanelCatLayout);
        PanelCatLayout.setHorizontalGroup(
            PanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        PanelCatLayout.setVerticalGroup(
            PanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suma-signo-mas.png"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PanelCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(PanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(PanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        opcion = "agregar";
        Producto producto = new Producto(0, "", 0.0, 0, 0);
           EditarProducto editarProducto = new EditarProducto(p_padre, categorias,producto, last_iduser, opcion, 0);
        p_padre.add(editarProducto);
        editarProducto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCat;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
